// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_na5VSwrPa6KEqLx-OXO-f7SvY-MSPU',
    appId: '1:157166033778:web:d7368453a952e9990d5beb',
    messagingSenderId: '157166033778',
    projectId: 'final-homework-hyunwoo',
    authDomain: 'final-homework-hyunwoo.firebaseapp.com',
    storageBucket: 'final-homework-hyunwoo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxnwXzewD7aVryInIBXfF0lK9LHIjMUM',
    appId: '1:157166033778:android:bb051749bf0bdc7d0d5beb',
    messagingSenderId: '157166033778',
    projectId: 'final-homework-hyunwoo',
    storageBucket: 'final-homework-hyunwoo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf86gwWp03UaaTwFZRkSSbAQLbkrXb5kI',
    appId: '1:157166033778:ios:53c4dcf0803838390d5beb',
    messagingSenderId: '157166033778',
    projectId: 'final-homework-hyunwoo',
    storageBucket: 'final-homework-hyunwoo.appspot.com',
    iosClientId: '157166033778-824n52siv7dm1ma79peju0df0nlu0r7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalHomeworkHyunwoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf86gwWp03UaaTwFZRkSSbAQLbkrXb5kI',
    appId: '1:157166033778:ios:53c4dcf0803838390d5beb',
    messagingSenderId: '157166033778',
    projectId: 'final-homework-hyunwoo',
    storageBucket: 'final-homework-hyunwoo.appspot.com',
    iosClientId: '157166033778-824n52siv7dm1ma79peju0df0nlu0r7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalHomeworkHyunwoo',
  );
}
